# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH key passphrase
        uses: appleboy/ssh-action@master        
        with:
          host: ${{ secrets.HOST }}          
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          timeout: 50s  # 30초 기본        
          script: |
            whoami
            ls -al
            echo "hi"
